apiVersion: v1
kind: Service
metadata:
  name: wav-to-flac-service
spec:
  selector:
    app: wav-to-flac-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer